# This is a Harness primitive.
# See also: library://meta-harness

name = "proj-quartz"
description = "Customer acquisition project knowledge and application for using Meta Harness Knowledge Agent with customer acquisition knowledge."
read_actors = ["actor://knowledge-agent"]
update_actors = ["actor://knowledge-agent"]
agent_excludes = [
  "app/node_modules/**",
  "app/.next/**",
]
